name: package-linux-appimage-self-hosted

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  package:
    uses: <owner>/gnustep-packager/.github/workflows/package-gnustep-app.yml@main
    with:
      manifest-path: packaging/package.manifest.json
      backend: appimage
      package-version: ${{ github.ref_name }}
      runs-on-appimage: '["self-hosted","linux","gnustep-clang"]'
      skip-default-host-setup: true
      preflight-shell: bash
      preflight-command: ./packaging/ci/preflight-appimage.sh
      run-validation: true
      run-smoke: true
      artifact-name: my-gnustep-linux-app
